// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MyLittleIRAF
{
	public partial class MainWindowController : NSView
	{
		public MainWindowController (IntPtr handle) : base (handle)
		{
		}
	}
}
