// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MyLittleIRAF
{
	public partial class NSOpe : NSViewController
	{
		public NSOpe (IntPtr handle) : base (handle)
		{
		}
	}
}
