// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using AppKit;

namespace MyLittleIRAF
{
	public partial class SheetViewController : NSViewController
	{
        private string _newName = "";
        private NSViewController _presentor;

        public string NewName
        {
            get { return _newName; }
            set { _newName = value; }
        }

        public NSViewController Presentor
        {
            get { return _presentor; }
            set { _presentor = value; }
        }

        public SheetViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewWillAppear()
        {
            base.ViewWillAppear();

            NewNameTextField.StringValue = NewName;

            NewNameTextField.Changed += (sender, e) =>
            {
                NewName = NewNameTextField.StringValue;
            };
        }
        private void CloseSheet()
        {
            Presentor.DismissViewController(this);
        }

        partial void RenameButton(NSObject sender)
        {
            RaiseSheetAccepted();
            CloseSheet();
        }

        partial void CancelButton(NSObject sender)
        {
            RaiseSheetCanceled();
            CloseSheet();
        }

        public EventHandler SheetAccepted;

        internal void RaiseSheetAccepted()
        {
            if (this.SheetAccepted != null)
                this.SheetAccepted(this, EventArgs.Empty);

        }

        public EventHandler SheetCanceled;

        internal void RaiseSheetCanceled()
        {
            if (this.SheetCanceled != null)
                this.SheetCanceled(this, EventArgs.Empty);
        }
    }
}
